name: humic
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ^3.5.3

dependencies:
  cupertino_icons: ^1.0.8
  firebase_core: ^3.6.0
  firebase_database: ^11.1.5
  firebase_storage: ^12.3.3
  fluentui_system_icons: ^1.1.264
  flutter:
    sdk: flutter
  get: 4.6.6
  google_fonts: ^6.2.1
  iconsax: ^0.0.8
  rive: ^0.13.15
  syncfusion_flutter_pdfviewer: ^27.1.53
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - "assets/images/"
    - "assets/rive/"
