// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBPx4vB7ggT2als-tBiZvM5_JSUAczJzi0',
    appId: '1:882098004569:web:5922be998ca4ce5682c748',
    messagingSenderId: '882098004569',
    projectId: 'hkiproductcataloghumic-944d5',
    authDomain: 'hkiproductcataloghumic-944d5.firebaseapp.com',
    storageBucket: 'hkiproductcataloghumic-944d5.appspot.com',
    measurementId: 'G-YYREP2MZ4S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOCNu3R3nFIN6IXat-PzAWCDhHEgQf6W0',
    appId: '1:882098004569:android:26fc08f49d2fa25082c748',
    messagingSenderId: '882098004569',
    projectId: 'hkiproductcataloghumic-944d5',
    storageBucket: 'hkiproductcataloghumic-944d5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDAeUxfYAlwkCtUEvK8EpLDbqe8Cqt6qu0',
    appId: '1:882098004569:ios:2d5f836a125cc64582c748',
    messagingSenderId: '882098004569',
    projectId: 'hkiproductcataloghumic-944d5',
    storageBucket: 'hkiproductcataloghumic-944d5.appspot.com',
    iosBundleId: 'com.example.humic',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDAeUxfYAlwkCtUEvK8EpLDbqe8Cqt6qu0',
    appId: '1:882098004569:ios:2d5f836a125cc64582c748',
    messagingSenderId: '882098004569',
    projectId: 'hkiproductcataloghumic-944d5',
    storageBucket: 'hkiproductcataloghumic-944d5.appspot.com',
    iosBundleId: 'com.example.humic',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBPx4vB7ggT2als-tBiZvM5_JSUAczJzi0',
    appId: '1:882098004569:web:5c3b69ccaeb6daa982c748',
    messagingSenderId: '882098004569',
    projectId: 'hkiproductcataloghumic-944d5',
    authDomain: 'hkiproductcataloghumic-944d5.firebaseapp.com',
    storageBucket: 'hkiproductcataloghumic-944d5.appspot.com',
    measurementId: 'G-WTK69G46ZG',
  );

}